name: Django CI/CD Pipeline

on:
  push:
    branches:
      - Kamal
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432

    steps:
      # Checkout repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run migrations and collect static files
      - name: Run Migrations and Collect Static
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      # Run tests
      - name: Run Tests
        run: python manage.py test

      # Deploy (optional - can be customized)
      - name: Deploy Application
        run: echo "Deploy your application steps here (e.g., SSH, AWS, Heroku, etc.)"
