name: Django CI/CD Pipeline

on:
  push:
    branches:
      - Kamal
      - main
      - hossam

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d mydatabase"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Migrations and Collect Static
        run: |
          cd django/mysite
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: List Files (Debugging)
        run: |
          cd django/mysite
          ls -R

      - name: Run Tests
        run: |
          cd django/mysite
          python manage.py test products.tests.test_login
          python manage.py test products.tests.test_payment
          python manage.py test products.tests.test_views
          python manage.py test products.tests.test_products
