name: Django CI/CD Pipeline

on:
  push:
    branches:
      - Kamal
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d mydatabase"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install PostgreSQL client
      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Navigate to the Django project directory and run migrations
      - name: Run Migrations and Collect Static
        run: |
          cd django/mysite  # Change directory to where manage.py is located
          python manage.py migrate
          python manage.py collectstatic --noinput

      # Run tests
      - name: Run Tests
        run: |
          cd django/mysite  # Change directory to where manage.py is located
          python manage.py test

      # Deploy
      - name: Deploy Application
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Add deployment steps here"
          # Example: Use SSH or a deployment tool like AWS CLI or Heroku CLI
